### ISSUE TITLE
wemos d1 mini 

### ISSUE THREAD

**Issue by MRHERT** [ChandlerMcCowan/8BitWiFiVisualizer#2]
thank you for you responding  for example lets take wemos d1 mini as an example i use it as access point but the signal is not strong as router it can go just throw a single wall how can we make that signal powerful is it possible do you have any suggestions please ?
thank you

**Comment by ChandlerMcCowan** [comment]
a WiFi Radio has to conform to certain standards, so it can be difficult to extend the  transmission power of compliant devices.

[A quick search found this article](https://wlan1nde.wordpress.com/2014/11/26/wlan-maximum-transmission-power-etsi/#:~:text=There%20exists%20two%20EIRP%20power,(63%20mW)%20for%20CCK.)

Think about the application and what the solution needs to solve the problem. Is WiFi the right type of radio to use, or could you experiment with other technologies to solve the problem?
